import { NextResponse } from 'next/server';
import { Redis } from '@upstash/redis';
import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

export const dynamic = 'force-dynamic';

const redis = Redis.fromEnv();

const SEARCH_INDEX_KEY = 'skills:search-index';
const SKILLS_DIR = path.join(process.cwd(), 'content', 'skills');

function buildFromFilesystem() {
  if (!fs.existsSync(SKILLS_DIR)) return [];

  return fs.readdirSync(SKILLS_DIR)
    .filter(f => f.endsWith('.md') && !f.startsWith('_'))
    .map(file => {
      const slug = file.replace(/\.md$/, '');
      const { data, content } = matter(fs.readFileSync(path.join(SKILLS_DIR, file), 'utf8'));

      const body = content
        .replace(/```[\s\S]*?```/g, '')
        .replace(/`[^`]+`/g, '')
        .replace(/^#{1,6}\s+/gm, '')
        .replace(/!\[.*?\]\(.*?\)/g, '')
        .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
        .replace(/[*_~]/g, '')
        .replace(/\n{2,}/g, ' ')
        .replace(/\n/g, ' ')
        .trim();

      return {
        slug: data.slug || slug,
        title: data.title || slug,
        description: data.description || '',
        categories: data.categories || [],
        tags: data.tags || [],
        featured: data.featured || false,
        mcp: data.mcp || false,
        author: data.author || '',
        repoUrl: data.repoUrl || '',
        date: data.date || '',
        excerpt: body.substring(0, 200) + '...',
        body,
      };
    });
}

/**
 * GET /api/search-index
 *
 * Serves the full skill search index for client-side Fuse.js search.
 * Reads from Redis blob (skills:search-index) — falls back to filesystem.
 * Cached at CDN edge for 5 minutes; stale-while-revalidate for 10 minutes.
 * Regenerated by running: npm run seed-meta
 */
export async function GET() {
  try {
    const cached = await redis.get<string>(SEARCH_INDEX_KEY);
    if (cached) {
      const data = typeof cached === 'string' ? JSON.parse(cached) : cached;
      return NextResponse.json(data, {
        headers: {
          'Cache-Control': 'public, max-age=300, stale-while-revalidate=600',
        },
      });
    }
  } catch {
    // Redis unavailable — fall through to filesystem
  }

  const data = buildFromFilesystem();
  return NextResponse.json(data, {
    headers: {
      'Cache-Control': 'public, max-age=300, stale-while-revalidate=600',
    },
  });
}
